export const GET_FOODS_REQ = "GET_FOODS_REQ";
export const GET_FOODS_SUCCESS = "GET_FOODS_SUCCESS";
export const GET_FOODS_FAIL = "GET_FOODS_FAIL";

export const DETAIL_FOOD_REQ = "DETAIL_FOOD_REQ";
export const DETAIL_FOOD_SUCCESS = "DETAIL_FOOD_SUCCESS";
export const DETAIL_FOOD_FAIL = "DETAIL_FOOD_FAIL";

export const ADD_FOOD_REQ = "ADD_FOOD_REQ";
export const ADD_FOOD_SUCCESS = "ADD_FOOD_SUCCESS";
export const ADD_FOOD_FAIL = "ADD_FOOD_FAIL";
export const ADD_FOOD_RESET = "ADD_FOOD_RESET";

export const EDIT_FOOD_REQ = "EDIT_FOOD_REQ";
export const EDIT_FOOD_SUCCESS = "EDIT_FOOD_SUCCESS";
export const EDIT_FOOD_FAIL = "EDIT_FOOD_FAIL";
export const EDIT_FOOD_RESET = "EDIT_FOOD_RESET";

export const DELETE_FOOD_REQ = "DELETE_FOOD_REQ";
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
export const DELETE_FOOD_FAIL = "DELETE_FOOD_FAIL";
export const DELETE_FOOD_RESET = "DELETE_FOOD_RESET";
